In [21]:
import sys
sys.path.append(r'D:\Usuario\Pablo\Escritorio\workspace\metodos_numericos')

from modulos.menu import menu
import numpy as np

In [22]:
menu("Metodo Jacobi que resuelve ecuaciones lineales con una matriz de N X N")



		████████████████████████████████████████████████████████████████████████████████████████████████████
		███                                                                                              ███
		███            Metodo Jacobi que resuelve ecuaciones lineales con una matriz de N X N            ███
		███                                                                                              ███
		███               Integrantes: Sol Lopez, Pablo Foglia, Juan Caceffo, Alejo Menini               ███
		███                                                                                              ███
		████████████████████████████████████████████████████████████████████████████████████████████████████





## Crear la matriz en la siguiente celda

In [23]:
matriz = np.array([[3, 4, -2],
                   [2, -3, 4],
                   [1, -2, 3]])
vector = np.array([-2, 6, 7])

matriz2 = np.array([[1, 1, -2], 
                    [1, -4, 1], 
                    [0, 2, -3]])
vector2 = np.array([11, 0, -3])

In [24]:
def calcular_determinante(matriz, vector_resultados):
    det = np.linalg.det(matriz)
    if det == 0:
        print("La matriz no tiene solución única.")
    else:
        matriz_triangular, vector_triangular = triangular_matriz(matriz, vector_resultados)
        print("Determinante:", det)
        print("Matriz triangular:")
        print(matriz_triangular)
        print("Vector triangular:")
        print(vector_triangular)

def triangular_matriz(matriz, vector_resultados):
    matriz_triangular = np.triu(matriz)
    vector_triangular = np.dot(matriz_triangular, vector_resultados)
    return matriz_triangular, vector_triangular

triangulada = calcular_determinante(matriz2, vector2)
triangulada

Determinante: 8.999999999999998
Matriz triangular:
[[ 1  1 -2]
 [ 0 -4  1]
 [ 0  0 -3]]
Vector triangular:
[17 -3  9]
